name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.300'
        
    - name: 'Run dotnet build'
      shell: bash
      run: |
        pushd ./AzureFunctions/AutomateAnythingEverything.Functions/
        dotnet build --configuration Release --output ./output
        popd
