name: Deploy-Azure-Functions

on:
  push:
    branches: [ master ]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'AzureFunctions/AutomateAnythingEverything.Functions/'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.300'
        
    - name: 'Run dotnet build'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.1.4
      with:
        app-name: fa-a3e-task-orchestrator-dev
        package: './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
